### PR TITLE
Enhancement/menu icons

### PR DESCRIPTION
**Pull request by HarrisSteven**
Added menu icons to all pages - both `index.html` and `app.html`.  These include:

- info icon: Displays a popup of the info cards that were previously displayed at the bottom of the screen. These were rearranged to be stacked vertically for better use of space.
- settings icon: Not yet implemented, to display the settings popup.
- statistics icon: Not yet completely implemented, to display a popup of the Zingchart graph.
- home icon: Redirects the user to the home page.  If in the middle of a session, displays a popup for the user to verify if they want to end their session.

### CODE REVIEW

**Comment by HarrisSteven** [comment]
Looking at this again, I think it would be better to also hide the icons on the page where they first sign in.

**Review by alanlwang1 — CHANGES_REQUESTED** [review]
On the screen where the user first enters their name, the menu icons are visible. Can you make it so the menu icons disappear on that screen?
I think everything else looks good though

**Comment by HarrisSteven** [comment]
Is there a way to rerun the firebase/cypress stuff after a new commit?

**Comment by alanlwang1** [comment]
I think if you go to actions -> the firebase deploy action -> rerun all jobs

**Pull request closed without merging**
