### PR TITLE
Add new library for stats modal, change stats modal behavior 

### LINKED ISSUE #144: [Enhancement] Stats Modal Changes
Display stats modal graph only when the user finishes more than one Pomo session
Investigate and implement a new graph API to replace ZingChart

### PR DESCRIPTION
**Pull request by alanlwang1**
Closes #144 
- Added new library [Chart.js ](https://www.chartjs.org/) for the stats modal line chart. This replaces our dependency on ZingChart. 
  - Reasoning for this change can be found in ADR added with this PR 
- Changed session data points on the chart to be labeled by session completion date, to give user more context (I needed something to fill the labels to use any of the charting libraries considered) 
- Added session completion dates to History, The backend `History` element now has this structure:
```
History {
  sessions: [
    { // individual session object 
      date: The completion date of the session
      tasklist: list of tasks in this session with expected, actual pomos
    }
  ]
}
```
- Integrated chart with existing SCSS for future integration with themes.  The CSS for `line-chart-colors` controls properties of the overall chart, while CSS for `line-chart-expected-color` and `line-chart-actual-color` control expected and actual Pomos line colors on the chart 
- Changed chart to only display when at least 3 sessions have been completed
- Revised unit tests to account for new behavior/backend structure 

 
image

### CODE REVIEW

**Comment by HarrisSteven** [comment]
Maybe the graph should also not pop up automatically at the end of the session when we don't have enough data.

**Comment by markbussard** [comment]
Content for the stats modal when empty is a little off in styling

Screenshot from 2022-05-27 16-45-53

**Comment by alanlwang1** [comment]
> Content for the stats modal when empty is a little off in styling
> 
> Screenshot from 2022-05-27 16-45-53

I think you reviewed this right after I merged from main and broke the css. Could you check again?

**Comment by markbussard** [comment]
@alanlwang1  Oh, yeah the styling looks good now. I also agree that maybe we should only auto show the stats modal when there is something to show off.

**Review by markbussard — APPROVED** [review]
Cool, looks good to me now.

**Pull request merged**
