### PR TITLE
Audio notifications toggle in settings

### PR DESCRIPTION
**Pull request by LJMNZS**
- Added another setting that allows users to toggle whether the ping sound should play with the notification
- Closes issue #186

### CODE REVIEW

**Comment by xingyuzzzhu** [comment]
Screen Shot 2022-06-04 at 3 50 50 PM
When toggle off during break, work session, short break and long break all become null, the timer only shows 00:00.

**Comment by LJMNZS** [comment]
> Screen Shot 2022-06-04 at 3 50 50 PM
> When toggle off during break, work session, short break and long break all become null, the timer only shows 00:00.

Did you happen to lower the timer values in localstorage before running, for testing? That can cause this error in settings as the timer drop downs don't get populated properly.

**Comment by LJMNZS** [comment]
> Screen Shot 2022-06-04 at 3 50 50 PM
> When toggle off during break, work session, short break and long break all become null, the timer only shows 00:00.

I just ran through a 25-minute timer and then used the audio toggle and the values in localStorage didn't become null. So I don't think this is an issue. Could someone else run a full session to test this?

**Comment by xingyuzzzhu** [comment]
I did change timer values to 1 min for testing, I'll try again without touching local storage

**Review by xingyuzzzhu — APPROVED** [review]

**Review by alanlwang1 — APPROVED** [review]

**Pull request merged**
