### PR TITLE
Enhancement/settings

### PR DESCRIPTION
**Pull request by HarrisSteven**
Adds functionality to the settings menu button.  When clicked, a modal will pop up allowing the user to configure the amount of time for work, short break, and long break sessions. There is also an option to reset the configuration to the default recommended times. User preferences are stored in local storage and updated each time the user saves new preferences. 

I have also moved the functionality of the info modal and the settings modal to their own classes to avoid cluttering the MenuIcons class with unrelated functions.

Note: the design for the modal will likely change as we implement a more general styling for all the menu popup modals.

### CODE REVIEW

**Review by alanlwang1 — CHANGES_REQUESTED** [review]
Should we make the settings and info classes into components so we don't need to duplicate the HTML for both pages? 
For example, this is how my stats/report modal is setup
```js  
constructor() {
    super();
    this.innerHTML = `
    <div id="stats-wrapper" class="modal-wrapper">
      <div class="container">
            <div class="modal-content">
              <h2 class="modal-title">Expected vs. Actual Pomos Per Session</h2>
              <div id="line-chart">
                <h3 id="line-chart-alt">You don't have any sessions recorded.<br>Click "Create Session" to create a new session!</h3>
              </div>
              <button id="stats-close" class="btn btn-primary">Close</button>
        </div>
      </div>
    </div>`;


    this.appendChild(wrapper);
    this.loadLineChart();
  }
```
And its added by just having `<stats-modal></stats-modal>`

**Comment by HarrisSteven** [comment]
> Should we make the settings and info classes into components so we don't need to duplicate the HTML for both pages? For example, this is how my stats/report modal is setup
> 
> ```js
> constructor() {
>     super();
>     const wrapper = document.createElement("div")
>     wrapper.classList.add("modal-wrapper");
>     wrapper.innerHTML = `
>       <div class="container">
>         <div class="row justify-content-center">
>           <div class="col">
>             <div class="modal-content card">
>               <h2 class="modal-title">Expected vs. Actual Pomos Per Session</h2>
>               <div id="lineChart"></div>
>             </div>
>           </div>
>         </div>
>       </div>`;
> 
>     this.appendChild(wrapper);
>     this.loadLineChart();
>   }
> ```
> 
> And its added by just having `<stats-modal></stats-modal>`

Yeah I was thinking of doing something like that, I'll change it

**Comment by alanlwang1** [comment]
Edited HTML in my comment to be cleaner, found that the bootstrap divs don't do much

**Comment by HarrisSteven** [comment]
I've removed the redundant HTML from index.html and app.html and moved those into custom HTML elements.  Now we have InfoModal.js and SettingsModal.js which define the HTML, then InfoController.js and SettingsController.js which define the functionality for those respective modals. MenuIcons.js puts these two together - it creates all the HTML for everything menu related and attaches the functionality to all user input.

**Comment by alanlwang1** [comment]
Is there a reason why we need to separate files into controller/component instead of just having everything in the component files?

**Comment by HarrisSteven** [comment]
Not really, could do it either way.  I was running into some issues with putting it all in one file where I set the HTML in the constructor then tried to select some of those elements after, but got null because they hadn't loaded in yet. I could probably fix that though if I spent more time on it.  How did you do the stats modal?

**Comment by markbussard** [comment]
@HarrisSteven 

As Alan stated, the logic from the `SettingsController` and `InfoController` should be moved and handled within their respective component files. 

In regards to the null issues, this is probably because the html / element hasn't been loaded into the DOM yet. This is where the lifecycle methods for web components come into play, specifically the `connectedCallback` method. You can do some searching, but here's a pretty good article I found explaining this: [web-components-lifecycle](https://bignerdranch.com/blog/learn-the-lifecycle-of-a-web-component-by-building-a-custom-element/)

**Comment by HarrisSteven** [comment]
Thanks, that makes sense

**Review by alanlwang1 — APPROVED** [review]

**Review by markbussard — APPROVED** [review]
Looks good to me.

**Pull request merged**
